/**
 * Passio Food Catalog API
 * Welcome to the [Passiolife](https://www.passiolife.com) Food Catalog API.  The Passiolife Catalog API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer)  methodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors.  All requests are authenticated using an `api-key` which can be obtained by signing up.  
 *
 * OpenAPI spec version: 0.2-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PassioFoodCatalog) {
      root.PassioFoodCatalog = {};
    }
    root.PassioFoodCatalog.FeedbackRequest = factory(root.PassioFoodCatalog.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FeedbackRequest model module.
   * @module model/FeedbackRequest
   * @version 0.2-beta
   */

  /**
   * Constructs a new <code>FeedbackRequest</code>.
   * @alias module:model/FeedbackRequest
   * @class
   * @param feedbackUuid {String} the uuid returned by the previous /classify method
   * @param rating {Number} a value from 0.0 to 1.0 indicating how good / satisfied  the user is with the result, where 1.0 is total satisfied. 
   * @param userChoice {String} the final choice of the user (label)
   */
  var exports = function(feedbackUuid, rating, userChoice) {
    var _this = this;

    _this['feedback_uuid'] = feedbackUuid;
    _this['rating'] = rating;
    _this['user_choice'] = userChoice;


  };

  /**
   * Constructs a <code>FeedbackRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeedbackRequest} obj Optional instance to populate.
   * @return {module:model/FeedbackRequest} The populated <code>FeedbackRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('feedback_uuid')) {
        obj['feedback_uuid'] = ApiClient.convertToType(data['feedback_uuid'], 'String');
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
      }
      if (data.hasOwnProperty('user_choice')) {
        obj['user_choice'] = ApiClient.convertToType(data['user_choice'], 'String');
      }
      if (data.hasOwnProperty('user_comment')) {
        obj['user_comment'] = ApiClient.convertToType(data['user_comment'], 'String');
      }
      if (data.hasOwnProperty('client_comment')) {
        obj['client_comment'] = ApiClient.convertToType(data['client_comment'], 'String');
      }
    }
    return obj;
  }

  /**
   * the uuid returned by the previous /classify method
   * @member {String} feedback_uuid
   */
  exports.prototype['feedback_uuid'] = undefined;
  /**
   * a value from 0.0 to 1.0 indicating how good / satisfied  the user is with the result, where 1.0 is total satisfied. 
   * @member {Number} rating
   */
  exports.prototype['rating'] = undefined;
  /**
   * the final choice of the user (label)
   * @member {String} user_choice
   */
  exports.prototype['user_choice'] = undefined;
  /**
   * The user can associate any comments to the evaluation
   * @member {String} user_comment
   */
  exports.prototype['user_comment'] = undefined;
  /**
   * (beta) The client can associate any comments or data to the evaluation.  Mainly used for future client specific training 
   * @member {String} client_comment
   */
  exports.prototype['client_comment'] = undefined;



  return exports;
}));


