/**
 * Passio Food Catalog API
 * Welcome to the [Passiolife](https://www.passiolife.com) Food Catalog API.  The Passiolife Catalog API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer)  methodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors.  All requests are authenticated using an `api-key` which can be obtained by signing up.  
 *
 * OpenAPI spec version: 0.2-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PassioFoodCatalog);
  }
}(this, function(expect, PassioFoodCatalog) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PassioFoodCatalog.ClassifyRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClassifyRequest', function() {
    it('should create an instance of ClassifyRequest', function() {
      // uncomment below and update the code to test ClassifyRequest
      //var instane = new PassioFoodCatalog.ClassifyRequest();
      //expect(instance).to.be.a(PassioFoodCatalog.ClassifyRequest);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new PassioFoodCatalog.ClassifyRequest();
      //expect(instance).to.be();
    });

    it('should have the property mediaB64 (base name: "media")', function() {
      // uncomment below and update the code to test the property mediaB64
      //var instane = new PassioFoodCatalog.ClassifyRequest();
      //expect(instance).to.be();
    });

  });

}));
